### ISSUE TITLE
Make usable zero value of clockwork.Clock

### ISSUE THREAD

**Issue by rekby** [jonboulle/clockwork#61] opened 2023-04-01 14:25 UTC
for this - change clockwork.Clock type from interface to struct or pointer with call system time functions by default (for zero value).

It allow make my own types usable with zero value without wrap time calls in my code.

**Comment by DPJacques** [comment] 2023-04-01 15:02
`NewFakeClockAt(t time.Time)` 
Is provided if you need a specific starting time.

`NewFakeClock()` returns a time that is not the zero the zero time or the unix epoch by design, due to their likelihood to be overlooked by default values. You should not rely on it's default value.

**Comment by rekby** [comment] 2023-04-01 15:50
I suggest to use zero value of ```clockwork.Clock``` as ```clockwork.NewRealClock()``` - for skip clock initialization in production code.

for example wrapper with same behavior: https://gist.github.com/rekby/a7f3e679e47604b28d22c7736d0ff388

**Comment by sagikazarmark** [comment] 2023-04-01 18:00
@rekby this is certainly an interesting proposal, but even your wrapper relies on an interface for allowing alternate implementations, so we can't just throw it away.

We can, however, add such a wrapper to the library (called `DefaultClock` or something). One could use that instead of the interface so that there is no need for initialization.

Let me play with that wrapper of yours a little.

**Comment by DPJacques** [comment] 2023-04-01 18:02
Gotcha, your issue title "usable zero value" confused me. I think I now understand that you are asking for custom clocks.

Changing this interface to a struct would break most users, because the interface is passed as a <pointer, type> whereas the struct would be passed by value copy unless users changed it to a pointer to struct throughout their code base. It is unlikely that change will be made.

 If you want to accomplish what you are seeking, `NewFakeClockAt(time.Time{})` does exactly what you are asking for with the current code. I don't really think providing alternatives types and wrappers should be added just for this feature request.

**Comment by sagikazarmark** [comment] 2023-04-01 18:05
@DPJacques I believe this is what @rekby is asking for:

```go
type MyStruct struct{
    Clock clockwork.Clock
}

var mystruct MyStruct

// Use Clock without initialization
mystruct.Clock.Now()
```

**Comment by DPJacques** [comment] 2023-04-01 18:19
Gotcha, the code helps understand a bit.

I maintain my position that I don't think avoiding initialization is a compelling requirement, in light of:
- The currently thin wrapper of realClock minimized performance overhead in production. I'd be remiss to add logic to the various clock functions as that seems costly at scale.
- Adding types or wrappers with alternative names feels like more overhead than it is worth to support avoiding initialization (see code block below). Alternative ways do do things is usually a tech debt flag.
- Myself and my colleagues, have questioned the value of optimizing for skipping initialization as a feature, as it is error prone in complex code. The best example I have is proto3's "default value is zero" convention, which I now understand the proto authors (and Go proto authors) to be trying to undo, making it more proto2 like and adding an API around the original struct implementation.

Requiring the code block above to be the following does not seem egregious to me:
```
type MyStruct struct{
    Clock clockwork.Clock
}

mystruct := MyStruct{clock: clockwork.NewRealClock}

mystruct.Clock.Now()
```

Not necessarily, my call, just my $0.02 :)

**Comment by sagikazarmark** [comment] 2023-04-01 18:38
See the linked PR.

I myself is not convinced yet that this belongs to this package, but I wanted to play with the idea.

**Comment by DPJacques** [comment] 2023-04-01 18:43
Totally makes sense. I'm glad I am not the only one who needs to convince themselves if something is a good idea or not :smile: 

I did my best to provide reasoning for my stance above. I don't think I could do any better than the PR you put out, although that reinforces my position: it feels like a lot of code for not a lot of benefit :/

**Comment by DPJacques** [comment] 2023-07-17 00:54
Closing this out since `clockwork.Clock`s status as an interface is the thing that makes it usage by `realClock` or `fakeClock`. This is a common use of interfaces in Go, and approaches to make a usable default value are hard to migrate to and use. The benefit gained is iminal in comparison.

**Closed by DPJacques** 2023-07-17 00:54 UTC
