### ISSUE TITLE
fakeTicker doesn't work as expected

### ISSUE THREAD

**Issue by seaguest** [jonboulle/clockwork#60] opened 2023-03-23 02:31 UTC
Hi, 

```
	fc := clockwork.NewFakeClock()

	ft := fc.NewTicker(1)
	fc.Advance(3)

	select {
	case x := <-ft.Chan():
		fmt.Println("1-------------", x)
	default:
	}

```

I am expecting have 3 print in above code, but it only print once, looks like the ticker is only triggered once, how can I trigger multiple times?

**Comment by DPJacques** [comment] 2023-03-23 02:43
There is no loop in the code above. It will only ever print once.

Also keep in mind ticks that are not received before the follow on tick are dropped: "The ticker will adjust the time interval or drop ticks to make up for slow receivers" - https://pkg.go.dev/time#Ticker

To accomplish what you want without race conditions, you need 3 goroutines running waiting on the tick, then call Advance(3). You should see each once of them fire once.

**Comment by seaguest** [comment] 2023-03-23 07:58
```
func main() {
	fc := clockwork.NewFakeClock()
	ft := fc.NewTicker(1)

	for i := 0; i < 3; i++ {
		go func() {
			select {
			case x := <-ft.Chan():
				fmt.Println("1-------------", x)
			default:
				fmt.Println("2-------------")
			}
		}()
	}

	fc.Advance(3)
	time.Sleep(time.Second)
}

-----OUTPUT----
2-------------
1------------- 2006-01-02 15:04:05.000000001 +0000 UTC
2-------------

```

**Comment by DPJacques** [comment] 2023-03-23 21:07
The `default:` case in your switch conditions leads you to race conditions. You are asking the program to run through the `for` loop as fast as possible, sidestepping the channel read if it can, so that is what happens. You just happen to catch 1 of the ticks in the code you have above.

- If you remove the `default:` case, you'll receive all the ticks, although not necessarily in order, since again, they all race.
- If you add a `Println` to ticker.go, you'll see it send in order, as expected.
- If you want to avoid race conditions on the caller side, you need to advance across each tick, take the action you want to take, then advance again.

From `clockworks` perspective, this is all working as intended. The caller side code is setting up a race condition.

**Comment by seaguest** [comment] 2023-03-24 03:18
@DPJacques 

Thanks for your reply!
it always print once even I removed the default case, it prints twice occasionally sometime.
I did a time.Sleep at the end to leave ticker enough time to get triggered.

**Comment by DPJacques** [comment] 2023-03-25 19:43
This is because the go routines have not started by the time `fc.Advance(3)` has completed, once again there is a race condition. If you add a `time.Sleep(1)` before your `fc.Advance(3)` you should see _most_ of them.

However, you are still inducing race conditions on the `clockwork` interface. If you want to avoid race conditions, you need to advance past every tick individually. If you don't do this, there will always be some amount of race condition in your code. There are ways to minimize those race conditions, but they will still be present. In all cases, `clockwork` is working as intended.

@sagikazarmark I think it would be reasonable to close this issue out.

**Comment by DPJacques** [comment] 2023-03-25 20:24
Example of waht I refer to in my comment above, the following code prints nothing:

```
func main() {
	fc := clockwork.NewFakeClock()
	ft := fc.NewTicker(1)

	for i := 0; i < 3; i++ {
		i := i
		go func() {
			fmt.Println("started: ", i)
			select {
			case x := <-ft.Chan():
				fmt.Println(i, " tim:: ", x)
			}
		}()
	}

	fc.Advance(3)
}
```

**Comment by DPJacques** [comment] 2023-03-25 20:27
Another example:

```
func main() {
	fc := clockwork.NewFakeClock()
	ft := fc.NewTicker(1)

	for i := 0; i < 3; i++ {
		i := i
		go func() {
			fmt.Println("started: ", i)
			select {
			case x := <-ft.Chan():
				fmt.Println(i, " time: ", x)
			}
		}()
	}

	fc.Advance(3)
	fmt.Println("advanced")
	time.Sleep(time.Second)
}
```

Output:
```
advanced
started:  2
2  time:  2006-01-02 15:04:05.000000001 +0000 UTC
started:  1
started:  0
```

**Comment by sagikazarmark** [comment] 2023-03-25 23:59
> @sagikazarmark I think it would be reasonable to close this issue out as working as intended.

I tend to agree.

@seaguest a couple more comments that hopefully understand you what's happening:

- similarly how the real Ticker works in the `time` package, the underlying channel in the fake ticker is a buffered channel with a buffer of one. That means if a channel is "full", the rest of the ticks will get lost.
- due to that fact and the race condition @DPJacques pointed out, you may not get all of the ticks

@DPJacques's examples accurately represent all that.

If you still believe there is a bug somewhere, please provide a test case or an example that proves there is one.

Hope this helps!

**Closed by sagikazarmark** 2023-03-25 23:59 UTC
